### ISSUE TITLE
Castoff -> Abgeworfenen vs Verstoßene

### ISSUE THREAD

**Issue by AurelioSilver** [AurelioSilver/tidesofnumenera-german-patch#4]
Castoff  wurde an viele Stellen als "Abgeworfene" übersetzt anstatt als "Verstoßene".

**Comment by MarcelAnderson** [comment]
35 Dateien enthalten "Abgeworfene". Zur korrekten Beurteilung sollte man jeden Satz einzeln prüfen. Ich würde daher dieses Issue schließen und den Stand so belassen.

**Comment by AurelioSilver** [comment]
Die Texte sollten nun alle überarbeitet sein.
