### ISSUE TITLE
Releases fehlen

### ISSUE THREAD

**Issue by MarcelAnderson** [AurelioSilver/tidesofnumenera-german-patch#6]
Für die Community fehlen noch einfach zu verwendende Release-Pakete. Ebenso eine Anleitung, wie man diese "installieren" kann.

**Comment by AurelioSilver** [comment]
Releases wollte ich machen, wenn ich einmal durch die Texte durch bin. Anleitung kannst du auch gerne schreiben, wenn du magst.

BTW, du solltest mal meine aktuellen Änderungen in dein Repo holen. :)

**Comment by MarcelAnderson** [comment]
Kannst du mir eine Email schreiben? Ich hätte ein paar interne Fragen zum Language Tool.
--> marcel@sladek-it.de

Danke vorab!

**Comment by AurelioSilver** [comment]
Release wurde nun erstellt.
